
import Foundation

/**
 The classic token filter does optional post-processing of terms that are generated by the classic tokenizer.
 
 This filter removes the english possessive from the end of words, and it removes dots from acronyms.
 
 [More information](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-classic-tokenfilter.html)
 */
public struct ClassicFilter: BasicTokenFilter, BuiltinTokenFilter {
    /// :nodoc:
    public static var typeKey = TokenFilterType.classic
    
    /// Holds the string that Elasticsearch uses to identify the filter type
    public let type = typeKey.rawValue
    /// :nodoc:
    public let name: String
    
    public init() {
        self.name = self.type
    }
}
